
export const DataContent = [
    {
        guideTitle: "Visiter Lindos et bien préparer son voyage",
        textTitle: "Egalement nommée la perle de Rhodes, Lindos supporte aisément la métaphore. Cette ville de la côte Est est sans aucun doute l'un des plus beaux sites de l'île grecque. Mer d'un bleu d'azur, maisons blanches empilées au pied de son acropole, théâtre antique et ruelles tortueuses, tous les ingrédients sont réunis pour que la magie s'opère le temps d'un séjour à Lindos.",
        titleLindos: "Histoire",
        histoireLindos: "Selon la légende (jamais confirmée par les fouilles), un culte pré-hellénique d'Athena Lindia avait lieu à l’emplacement de l’acropole vers 2500 av. J.-C. (âge néolithique). Dix siècles plus tard, les Achéens s'installent, mais il faut attendre le Xe s. av. J.-C. (période géométrique) et l'arrivée des Doriens pour que Lindos rivalise, puis dépasse les cités de Kamiros et de lalyssos. Ses habitants commerçaient avec Chypre et l'Égypte dès le VIIe s. av. J.-C. Dans la première partie du VIe s. av. J.-C., Kleoboulos, connu comme l'un des sept sages, gouverna pendant 40 ans sa cité très démocratiquement. Il améliora le sanctuaire de la déesse, renommée dans toute la Grèce pour ses miracles, construisit un temple plus grand et offra une couronne d'or à la statue en bois déjà existante. En 342 av. J.-C., le temple de Kleoboulos est ravagé par un incendie et les Lindiens le rebâtissent dans le style dorique avant d'ériger une nouvelle statue de la déesse. Ses nombreux miracles attirent les offrandes, mais seuls les piédestaux des statues offertes ont été conservés. Lindos reste le grand centre religieux de l'île bien longtemps encore après la fondation de Rhodes.",
        infoContainer: "Ville classée monument historique depuis très longtemps, Lindos a banni l'automobile. Pour le bonheur des touristes. Elle n'en a pas moins organisé leur accueil, prévoyant un parking à l'entrée de la ville et une navette qui stationne près de l'arrêt de bus des autocars en provenance de la ville de Rhodes.",
        textContent: "Lindos est l'un des trois sites antiques de l'île grecque de Rhodes. C'en est aussi aujourd'hui, la deuxième destination touristique. A juste titre. Car comme surgie d'un livre d'images, Lindos correspond à la Grèce de l'imaginaire collectif. Lindos s'est forgée une identité sur les vestiges qui ont fait sa prospérité de ville antique commerçante et enviée de tous. Son acropole dominant la baie est encore aujourd'hui prise d'assaut. Cette fois par des touristes qui y montent à pied sous un soleil de plomb suivant la rue principale, l'Odos Akropoleos ou qui préfèrent enfourcher l'un de ces petits ânes qui gravissent la colline. L'ascension en vaut le coup. De magnifiques colonnes, notamment celles du temple Athena Lindia offrent un premier plan d'une blancheur aveuglante à la baie de Lindos. Le spectacle se déplace du Nord avec vue imprenable sur le port ",
        textContentTwo: "naturel de Lindos au Sud dans la baie de St Paul en glissant vers l'Est sur les toîts de la ville. Dans la journée, Lindos résonne des cris des âniers et des exclamations des voyageurs qui seuls viennent troubler la torpeur des ruelles si méditerranénnes. Mais le soir revenu, lorsque le calme regagne Lindos, apparaissent alors d'autres trésors de cette ville égéenne marquée par le passage des Hospitaliers de Saint-Jean-de-Jérusalem et par l'empire ottoman. Mais séjourner à Lindos est aussi l'occasion d'une rencontre avec la culture grecque, ses églises orthodoxes comme celle du centre consacrée à la Vierge Marie également nommée Panagie, ou encore la chapelle Saint-George Pahimahiotis.",
        lastOneTitle: "Visites à Lindos",
        lastTwoTitle: "Sorties à Lindos",
        lastThreeTitle: "Transports et déplacements à Lindos",
        lastOneText: "L'acropole avec son temple d'Athena et celui de Phsithyros. Et ses vieilles dames qui vendent leurs nappes brodées. Les villas de capitaines et de notables datant du XVIIème siècle avec leurs cours intérieures décorées de mosaîque de galets. L'Eglise Sainte Marie (Panagie), la place de liberté dénommée Platia Elefterias dans le centre de la ville, l'Odos Akropoleos artère principale de Lindos où se concentre toute l'activité et bien entendu sa plage de sable fin.",
        lastTwoText: "Encombrée par les touristes la journée, Lindos se remplit la nuit de noctambules. Ses bars reflètent la généreuse hospitalité des Grecs et offrent la fraîcheur sur des terrasses (parfois même sur trois niveaux) dominant les toîts de la ville et permettant une vue inédite sur l'Acropole. Sur la plage bars et restaurants sont également fréquentés par les jeunes de la ville.",
        lastThreeText: "Lindos ajoute à son charme l'absence d'automobiles. On y accède donc en bus ou en bâteau ou encore en voiture particulière qu'il faudra laisser à l'entrée de la ville. Une voiture de location à Lindos n'est cependant pas superflue puisqu'elle permettra de sillonner le reste de l'île et notamment les montagnes où les villageois savent se faire si accueillants.",
    },
]